name: RAYPRO
favicon: null
layout_spectrum: 0.3556309451814741
typography_spectrum: 0.4517194516956806
title: RAY PRO PHOTOGRAPHY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.12166418042033911
  lightness: 0.1885305973701179
  saturation: 0.9026324544101954
  rhythmicContrast: 0.5987314023077488
purpose: []
